kanban
  title WIP 限制示例

  backlog[需求池] wip:10
    task1[需求A]
    task2[需求B]
    task3[需求C]

  todo[待开始] wip:5
    task4[任务1]
    task5[任务2]

  doing[开发中] wip:3
    task6[开发任务A]
    task7[开发任务B]
    task8[开发任务C]
    task9[开发任务D]

  review[审查] wip:2
    task10[审查1]

  done[完成]
    task11[已完成任务]