name: SmoothMarkdownDemo
options:
  bundleIdPrefix: com.jackcaow
  deploymentTarget:
    iOS: '17.0'
packages:
  SmoothMarkdown:
    path: ..
targets:
  SmoothMarkdownDemo:
    type: application
    platform: iOS
    sources:
      - path: SmoothMarkdownDemo
        excludes:
          - Examples/**
      - path: SmoothMarkdownDemo/Examples
        buildPhase: resources
      - path: ../Tests/SmoothMarkdownTests/Fixtures/FlutterREADME.md
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jackcaow.smoothmarkdown.demo
        SWIFT_VERSION: '5.9'
    info:
      path: SmoothMarkdownDemo/Info.plist
      properties:
        UILaunchScreen: {}
    dependencies:
      - package: SmoothMarkdown
  SmoothMarkdownDemoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - SmoothMarkdownDemoUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jackcaow.smoothmarkdown.demo.uitests
        SWIFT_VERSION: '5.9'
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: SmoothMarkdownDemo
  SmoothMarkdownDemoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SmoothMarkdownDemoTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jackcaow.smoothmarkdown.demo.tests
        SWIFT_VERSION: '5.9'
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SmoothMarkdownDemo.app/SmoothMarkdownDemo"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: SmoothMarkdownDemo
  SmoothMarkdownPerformanceUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: SmoothMarkdownDemo
